import math
from math import fabs, ceil, cos, acos, tan, asin, sin, atan, comb, factorial, perm, acosh, asinh, atanh, atan2, copysign,degrees, dist
from math import erf, erfc, exp, expm1, floor, fmod
print(ceil(1))
print(fabs(-1))
print(cos(1.2))
print(tan(math.PI/2))
print(asin(1))
print(sin(1.3))
print(atan(100))
print(comb(10,7))
print(factorial(10))
print(perm(5,None))
print(acosh(9))
print(asinh(10))
print(atanh(0.9))
print(atan2(2,1))
print(copysign(1, -1))
print(degrees(3))
print(dist((1.0,2), (3,4)))
print(erf(1.3))
print(erfc(1.9))
print(exp(2))
print(expm1(2))
print(floor(1.6))
print(fmod(1.3, 3))