f = open('src/test/resources/testpy/test.txt', 'rw')
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print("---------")
# print(f.read())
# print(f.read())
# print(f.read())


print(f.write("heeloooo\n"))
f.write("fjfsakj\n")
f.write("ffsffs\n")
print(f.readline())
print(f.readline())
print(f.read())
# f.seek(0)
# print(f.read())
